language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python manage.py db upgrade
script: coverage run manage.py test
env:
  - SECRET_KEY=not-so-secret export AUTHY_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
after_success:
  - coveralls
