"""empty message

Revision ID: 1369ead26210
Revises: None
Create Date: 2015-10-21 13:37:57.134839

"""

# revision identifiers, used by Alembic.
revision = '1369ead26210'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('authy_id', sa.Integer(), nullable=True),
    sa.Column('authy_status', sa.Enum('unverified', 'onetouch', 'sms', 'token', 'approved', 'denied', name='authy_statuses'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
