"""create user table

Revision ID: f2733ec8543e
Revises: 
Create Date: 2018-02-16 16:05:46.735172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2733ec8543e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=64), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('full_name', sa.String(length=256), nullable=True),
        sa.Column('country_code', sa.Integer(), nullable=True),
        sa.Column('phone', sa.String(length=30), nullable=True),
        sa.Column('authy_id', sa.Integer(), nullable=True),
        sa.Column(
            'authy_status',
            sa.Enum(
                'unverified',
                'onetouch',
                'sms',
                'token',
                'approved',
                'denied',
                name='authy_statuses',
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
